output_path: "/scratch/indikar_root/indikar1/cstansbu/scpc_test/"
ref_paths: "config/reference_paths.txt"
fastq_paths: "config/fastq_paths.txt"
snps_paths: "config/snps_paths.txt"
gtf_paths: "config/gtf_paths.txt"
chromosome_list: "config/chromList.txt"
phase_against: 'GRCm39'
enzyme: 'NlaIII'
indexer: "minimap2 -d"
minimap_args : "-ax map-ont"
bwa_args : "bwasw -b 5 -q 2 -r 1 -T 15 -z 10"
threads: 36
mapq_threshold: 20
