output_path: "/scratch/indikar_root/indikar1/cstansbu/scpc_test/"
ref_paths: "config/reference_paths.txt"
fastq_paths: "config/fastq_paths.txt"
pod5_paths: "config/pod5_paths.txt"
snps_paths: "config/snps_paths.txt"
gtf_paths: "config/gtf_paths.txt"
barcode_path: "config/barcodes.txt"
dorado_path: "/nfs/turbo/umms-indikar/shared/projects/poreC/data/dorado/dorado-0.5.3-linux-x64/bin/dorado"
dorado_model: "/nfs/turbo/umms-indikar/shared/projects/poreC/data/dorado/models/dna_r10.4.1_e8.2_400bps_sup@v4.2.0"
dorado_min_qscore: 7
longread_path: "/nfs/turbo/umms-indikar/shared/projects/poreC/data/phasing_tools/longphase_linux-x64"
chromosome_list: "config/chromList.txt"
phase_against: 'GRCm39'
enzyme: 'NlaIII'
indexer: "minimap2 -d"
minimap_args : "-ax map-ont -k 15 -w 5"
threads: 36
mapq_threshold: 20
