output_path: "/scratch/indikar_root/indikar1/shared_data/single-cell-pore-c/"
ref_paths: "config/reference_paths.txt"
fastq_paths: "config/fastq_paths.txt"
snps_paths: "config/snps_paths.txt"
gtf_paths: "config/gtf_paths.txt"
barcode_path: "config/barcodes.txt"
fastqc_adapters: "config/adapter_list.txt"
fastqc_contaminants: "config/contaminant_list.txt"
longread_path: "/nfs/turbo/umms-indikar/shared/projects/poreC/data/phasing_tools/longphase_linux-x64"
chromosome_list: "config/chromList.txt"
n_mismatches: 3
enzyme: 'NlaIII'
indexer: "minimap2 -d"
minimap_args : "-ax map-ont -k 15 -w 5"
threads: 36
mapq_threshold: 20
